# Generated by Django 4.2.4 on 2024-02-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Confronto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateField()),
                ('gols_time_a', models.IntegerField(default=0)),
                ('gols_time_b', models.IntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('posicao', models.CharField(choices=[('Goleiro', 'Goleiro'), ('Lateral', 'Lateral'), ('Zagueiro', 'Zagueiro'), ('Volante', 'Volante'), ('Meia', 'Meia'), ('Ponta', 'Ponta'), ('Atacante', 'Atacante')], max_length=20)),
                ('data_nascimento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('confronto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.confronto')),
                ('jogador_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_entrada', to='analise.jogador')),
                ('jogador_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_saida', to='analise.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('link_video', models.URLField(blank=True, null=True)),
                ('coordenadaX', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadaY', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadaXFinal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadaYFinal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('confronto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.confronto')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.jogador')),
                ('tipo_lance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='analise.tipo_lance')),
            ],
        ),
        migrations.AddField(
            model_name='confronto',
            name='time_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrontos_time_a', to='analise.time'),
        ),
        migrations.AddField(
            model_name='confronto',
            name='time_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confrontos_time_b', to='analise.time'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Escalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confronto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.confronto')),
                ('jogadores', models.ManyToManyField(related_name='escalacoes', to='analise.jogador')),
            ],
            options={
                'unique_together': {('confronto',)},
            },
        ),
    ]
