# Generated by Django 4.2.4 on 2024-02-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_lance',
            old_name='nome',
            new_name='tipo_lance',
        ),
    ]
