# Generated by Django 4.2.4 on 2024-02-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_rename_nome_tipo_lance_tipo_lance'),
    ]

    operations = [
        migrations.AddField(
            model_name='confronto',
            name='acrescimo1tempo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confronto',
            name='acrescimo2tempo',
            field=models.IntegerField(default=0),
        ),
    ]
