# Generated by Django 4.2.4 on 2024-02-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0003_confronto_acrescimo1tempo_confronto_acrescimo2tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituicao',
            name='primeiro_tempo',
            field=models.BooleanField(default=False),
        ),
    ]
