# Generated by Django 4.2.4 on 2024-02-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0004_substituicao_primeiro_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='tempo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
